name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    # FIXME
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Racket
        run: |
          sudo apt-get install racket
          
