name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    # FIXME
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install apt dependencies
        run: |
          sudo apt-get install racket sox vorbis-tools flac

      - name: Run tests
        run: |
          raco test -m test
          
